INSERT INTO dbo.Persons (LastName,FirstName,Sex,DateOfBirth,DateOfDeath,Hoetown,PlaceOfBirth,PlaceOfResidence,Profession) VALUES
	('Durscher','Jakob','male','1964-10-02','','Glarus Süd','Burgdorf BE','Oberstammheim','Metzger'),
	('Durscher Haussener','Hanni','female','1964-10-02','','Glarus Süd','Burgdorf BE','Oberstammheim','Verkäuferin'),
	('Durscher','Markus','male','1964-10-02','','Glarus Süd','Burgdorf BE','8050 Zürich Oerlikon','Wirtschaftsinformatiker'),
	('Durscher Leupp','Corinne','female','1975-12-25','','Uster','Uster','8050 Zürich Oerlikon','Sportlehrerin'),
	('Durscher','Nils','male','2005-11-28','','Glarus Süd','Zürich','8050 Zürich Oerlikon','Schüler'),
	('Durscher','Jasmin','female','2008-08-15','','Glarus Süd','Zürich','8050 Zürich Oerlikon','Schülerin'),
	('Durscher','Thomas','male','1965-11-17','','Glarus Süd','Burgdorf BE','Appenzell','Informatiker'),
	('Durscher Kuhn','Ingrid','female','1965-11-17','','Glarus Süd','Burgdorf BE','Aargau','KV'),
	('Durscher','René','male','1969-09-15','','Glarus Süd','Burgdorf BE','Oberengstringen ZH','Postangestellter'),
	('Steiger','Tanja','female','1965-11-17','','Glarus Süd','Burgdorf BE','Aargau','Gastronomin'),
	('Suh','Lei','female','1965-11-17','','Shanghai','Shanhai','Oberengstringen ZH','Postangestellte'),
	('Durscher','David','male','1990-06-01','','Glarus Süd','Frauenfeld','Winterthur','Gastronom'),
	('Suh','Anqi','female','1990-01-01','','Shanghai','Shanghai','Oberengstringen ZH','Studentin'),
	('Durscher','Renato','male','1990-11-07','','Glarus Süd','Zürich','Aargau','Fahrradmechaniker'),
	('Durscher','Romano','male','1990-11-07','','Glarus Süd','Zürich','Aargau','Automechaniker')
